export const ALL_FACULTY_REQUEST = 'ALL_FACULTY_REQUEST';
export const ALL_FACULTY_SUCCESS = 'ALL_FACULTY_SUCCESS';
export const ALL_FACULTY_FAIL = 'ALL_FACULTY_FAIL';

export const SINGLE_FACULTY_REQUEST = 'SINGLE_FACULTY_REQUEST';
export const SINGLE_FACULTY_SUCCESS = 'SINGLE_FACULTY_SUCCESS';
export const SINGLE_FACULTY_FAIL = 'SINGLE_FACULTY_FAIL';



export const CLEAR_ERRORS = 'CLEAR_ERRORS';
